;;; esh-autosuggest-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from esh-autosuggest.el

(autoload 'esh-autosuggest "esh-autosuggest" "\
`company-mode' backend to provide eshell history suggestion.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "esh-autosuggest" '("esh-autosuggest-"))

;;; End of scraped data

(provide 'esh-autosuggest-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; esh-autosuggest-autoloads.el ends here
